# Form implementation generated from reading ui file 'dialog_CreateAccount.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback

import pyodbc
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    id = ""

    def init(self, id=''):
        self.id = id

    def set_id(self, id):
        self.id = id;

    def get_id(self):
        return self.id;

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 247)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 10, 401, 21))
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 50, 361, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.idEmp = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idEmp.setFont(font)
        self.idEmp.setObjectName("idEmp")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.idEmp)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.firstnameEmp = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstnameEmp.setFont(font)
        self.firstnameEmp.setObjectName("firstnameEmp")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.firstnameEmp)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.lastnameEmp = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastnameEmp.setFont(font)
        self.lastnameEmp.setObjectName("lastnameEmp")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lastnameEmp)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.inputUsername = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputUsername.setFont(font)
        self.inputUsername.setObjectName("inputUsername")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputUsername)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_9)
        self.roleCbb = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roleCbb.setFont(font)
        self.roleCbb.setObjectName("roleCbb")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.roleCbb)
        self.inputPassword = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputPassword.setFont(font)
        self.inputPassword.setObjectName("inputPassword")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputPassword)
        self.okBtn = QtWidgets.QPushButton(Dialog)
        self.okBtn.setGeometry(QtCore.QRect(220, 210, 56, 17))
        self.okBtn.setObjectName("okBtn")
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(290, 210, 56, 17))
        self.cancelBtn.setObjectName("cancelBtn")
        self.loadCbbRole()
        self.loadData()
        self.okBtn.clicked.connect(self.okBtnClicked)
        # self.cancelBtn.clicked.connect(self.cancelBtnClicked())
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def loadData(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            cursor = conn.cursor()
            sql = cursor.execute("SELECT * FROM ACCOUNT WHERE ACCOUNT.IDEMP = '" + self.get_id() + "'")
            temp = sql.fetchone()
            username = temp[0]
            self.inputUsername.setText(username)
            password = temp[1]
            self.inputPassword.setText(password)
            cursor1 = conn.cursor()
            role = temp[4]
            sql1 = cursor1.execute("SELECT ROLENAME FROM ROLE WHERE ROLE.IDROLE = '" + str(role) + "'")
            roleCbb = sql1.fetchone()[0]
            self.roleCbb.setCurrentText(roleCbb)
            cursor2 = conn.cursor()
            sql2 = cursor2.execute("SELECT IDEMP, FISRTNAME, LASTNAME FROM EMPLOYEE WHERE EMPLOYEE.IDEMP = '" + self.get_id() + "'")
            temp2 = sql2.fetchone()
            id = temp2[0]
            self.idEmp.setText(str(id))
            firstname = temp2[1]
            self.firstnameEmp.setText(str(firstname))
            lastname = temp2[2]
            self.lastnameEmp.setText(str(lastname))
            self.inputUsername.setEnabled(False)
        except:
            traceback.print_exc()

    def loadCbbRole(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            cursor = conn.cursor()
            sql = cursor.execute("SELECT * FROM ROLE")
            for row in sql:
                self.roleCbb.addItem(str(row[1]))
        except:
            traceback.print_exc()

    def okBtnClicked(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            password = self.inputPassword.text()
            print(password)
            role = self.roleCbb.currentText()
            cursor = conn.cursor()
            sql = cursor.execute("SELECT IDROLE FROM ROLE WHERE ROLE.ROLENAME = '" + role + "'")
            newRole = sql.fetchone()[0]
            print(newRole)
            print(type(str(newRole)))
            cursor1 = conn.cursor()
            print(self.get_id())
            sql1 = cursor1.execute("UPDATE ACCOUNT SET PASSWORD = '" + str(password) + "', IDROLE = '" + str(newRole) + "' WHERE ACCOUNT.IDEMP = '" + self.get_id() + "'")
        except:
            traceback.print_exc()

    # def cancelBtnClicked(self):
    #     try:
    #
    #     except:
    #         traceback.print_exc()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\">THÔNG TIN NHÂN VIÊN </p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">TẠO TÀI KHOẢN</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">ID Nhân viên:</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Họ:</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Tên:"))
        self.label_6.setText(_translate("Dialog", "Tên tài khoản:"))
        self.label_8.setText(_translate("Dialog", "Mật khẩu:"))
        self.label_9.setText(_translate("Dialog", "Quyền:"))
        self.okBtn.setText(_translate("Dialog", "OK"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    sever = 'localhost'
    database = 'HTTM'
    conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                          "Server=localhost;"
                          "Database=HTTM;"
                          "Trusted_connection=yes;"
                          "MARS_Connection=yes")
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
