# Form implementation generated from reading ui file 'dialog_EmployeeInfo.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import re
from datetime import datetime, date
from locale import currency

from PyQt6 import QtCore, QtGui, QtWidgets

from PyQt6.QtWidgets import QMessageBox
import traceback
import pyodbc
import dialog_EmployeeCV
import employeeMain
import employeeProduct
from employeeProduct import convertAccentedToUnsigned


class Ui_Dialog(object):
    def setupUi(self, Dialog, idEmpPara):
        Dialog.setObjectName("Dialog")
        Dialog.resize(395, 455)
        self.diaBtnYesNo = QtWidgets.QDialogButtonBox(Dialog)
        self.diaBtnYesNo.setGeometry(QtCore.QRect(30, 382, 341, 32))
        self.diaBtnYesNo.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.diaBtnYesNo.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.diaBtnYesNo.setObjectName("diaBtnYesNo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 17, 391, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lblidEmp = QtWidgets.QLabel(Dialog)
        self.lblidEmp.setGeometry(QtCore.QRect(50, 60, 91, 16))
        self.lblidEmp.setText("")
        self.lblidEmp.setObjectName("lblidEmp")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ledtFirstName = QtWidgets.QLineEdit(Dialog)
        self.ledtFirstName.setGeometry(QtCore.QRect(50, 89, 91, 21))
        self.ledtFirstName.setObjectName("ledtFirstName")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(150, 90, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ledtLastName = QtWidgets.QLineEdit(Dialog)
        self.ledtLastName.setGeometry(QtCore.QRect(180, 89, 191, 21))
        self.ledtLastName.setObjectName("ledtLastName")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.dedtBirthDay = QtWidgets.QDateEdit(Dialog)
        self.dedtBirthDay.setGeometry(QtCore.QRect(91, 118, 110, 22))
        self.dedtBirthDay.setObjectName("dedtBirthDay")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 150, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ledtAddress = QtWidgets.QLineEdit(Dialog)
        self.ledtAddress.setGeometry(QtCore.QRect(70, 148, 301, 21))
        self.ledtAddress.setObjectName("ledtAddress")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 180, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.ledtPassword = QtWidgets.QLineEdit(Dialog)
        self.ledtPassword.setGeometry(QtCore.QRect(130, 234, 241, 21))
        self.ledtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ledtPassword.setObjectName("ledtPassword")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(40, 235, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lblAccountName = QtWidgets.QLabel(Dialog)
        self.lblAccountName.setGeometry(QtCore.QRect(110, 207, 111, 20))
        self.lblAccountName.setText("")
        self.lblAccountName.setObjectName("lblAccountName")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(40, 207, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(20, 295, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.btnCV = QtWidgets.QPushButton(Dialog)
        self.btnCV.setGeometry(QtCore.QRect(48, 288, 85, 29))
        self.btnCV.setObjectName("btnCV")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(20, 322, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lblMajor = QtWidgets.QLabel(Dialog)
        self.lblMajor.setGeometry(QtCore.QRect(120, 322, 101, 16))
        font = QtGui.QFont()
        font.setBold(False)
        self.lblMajor.setFont(font)
        self.lblMajor.setText("")
        self.lblMajor.setObjectName("lblMajor")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(20, 350, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lblDepartment = QtWidgets.QLabel(Dialog)
        self.lblDepartment.setGeometry(QtCore.QRect(99, 350, 81, 16))
        self.lblDepartment.setText("")
        self.lblDepartment.setObjectName("lblDepartment")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(40, 261, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.ledtConfirmPass = QtWidgets.QLineEdit(Dialog)
        self.ledtConfirmPass.setGeometry(QtCore.QRect(130, 260, 241, 21))
        self.ledtConfirmPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ledtConfirmPass.setObjectName("ledtConfirmPass")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.mainWindowCopy = Dialog
        self.idEmp = idEmpPara
        self.idCV = ""

        # Self functions
        self.loadDataFromDB()
        self.btnCV.clicked.connect(self.clickToOpenCV)
        self.diaBtnYesNo.accepted.connect(self.clickToChangeInfo)
        self.diaBtnYesNo.rejected.connect(self.clickToBackMainEmpWindow)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">THÔNG TIN CÁ NHÂN</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "ID:"))
        self.label_4.setText(_translate("Dialog", "Họ:"))
        self.ledtFirstName.setText(_translate("Dialog", "Nguyễn"))
        self.label_5.setText(_translate("Dialog", "Tên:"))
        self.ledtLastName.setText(_translate("Dialog", "Văn A"))
        self.label_6.setText(_translate("Dialog", "Ngày sinh:"))
        self.label_7.setText(_translate("Dialog", "Địa chỉ:"))
        self.ledtAddress.setText(_translate("Dialog", "HCM"))
        self.label_8.setText(_translate("Dialog", "Thông tin tài khoản:"))
        self.ledtPassword.setText(_translate("Dialog", "sfsdfdsfdsf"))
        self.label_9.setText(_translate("Dialog", "Mật khẩu:"))
        self.label_11.setText(_translate("Dialog", "Tài khoản:"))
        self.label_12.setText(_translate("Dialog", "CV:"))
        self.btnCV.setText(_translate("Dialog", "Xem"))
        self.label_13.setText(_translate("Dialog", "Chuyên ngành:"))
        self.label_15.setText(_translate("Dialog", "Phòng ban:"))
        self.label_17.setText(_translate("Dialog", "Xác nhận MK:"))
        self.ledtConfirmPass.setText(_translate("Dialog", "sfsdfdsfdsf"))

    def loadDataFromDB(self):
        try:
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            cursor = conn.cursor()
            cursor.execute("""SELECT EMP.IDEMP, EMP.FISRTNAME, EMP.LASTNAME, EMP.DATEOFBIRTH, EMP.ADDRESS,
                ACC.USERNAME, ACC.PASSWORD, CV.IDCV, MAJ.MAJOR, DEP.DEPNAME
                FROM EMPLOYEE EMP, ACCOUNT ACC, CV, MAJOR MAJ, DEPARTMENT DEP
                WHERE EMP.IDEMP = (?)
                AND EMP.USERNAME = ACC.USERNAME
                AND EMP.IDVC = CV.IDCV
                AND EMP.IDMAJOR = MAJ.IDMAJOR
                AND EMP.IDDEP = DEP.IDDEP""", self.idEmp)
            # Keyword fetch explanation: resolve record result from DB to an array
            # whose elements are arrays (fetchall, fetchmany)
            # , an array whose elements are variables having its own type (fetchone)
            sqlQuery = cursor.fetchall()
            for element, index in zip(sqlQuery, range(999)):  # fun experiment
                print(f"-----Line {index + 1}:")
                self.lblidEmp.setText(str(element[0]))
                self.ledtFirstName.setText(element[1])
                self.ledtLastName.setText(element[2])
                self.dedtBirthDay.setDate(element[3])
                self.ledtAddress.setText(element[4])
                self.lblAccountName.setText(element[5])
                self.ledtPassword.setText(element[6])
                self.ledtConfirmPass.setText(element[6])
                self.idCV = element[7]
                self.lblMajor.setText(element[8])
                self.lblDepartment.setText(element[9])
        except:
            traceback.print_exc()

    def clickToOpenCV(self):
        try:
            self.windowEmployeeCV = QtWidgets.QDialog()
            self.ui = dialog_EmployeeCV.Ui_Dialog()
            self.ui.setupUi(self.windowEmployeeCV, self.idEmp)
            self.windowEmployeeCV.show()
            self.mainWindowCopy.close()
        except:
            traceback.print_exc()

    def clickToChangeInfo(self):
        try:
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            firstNameEmp = self.ledtFirstName.text()
            lastNameEmp = self.ledtLastName.text()
            birthDayEmp = self.dedtBirthDay.text()
            addressEmp = self.ledtAddress.text()
            passwordEmp = self.ledtPassword.text()
            confirmPasswordEmp = self.ledtConfirmPass.text()
            accountNameEmp = self.lblAccountName.text()

            unsignedFirstNameEmp = employeeProduct.convertAccentedToUnsigned(firstNameEmp)
            unsignedLastNameEmp = employeeProduct.convertAccentedToUnsigned(lastNameEmp)
            unsignedAddressEmp = employeeProduct.convertAccentedToUnsigned(addressEmp)
            unsignedPasswordEmp = employeeProduct.convertAccentedToUnsigned(passwordEmp)

            if "" in [firstNameEmp, lastNameEmp, addressEmp, passwordEmp, confirmPasswordEmp]:
                self.showMessageBox("Please fill full information!")
                return

            if not passwordEmp == confirmPasswordEmp:
                self.showMessageBox("Two passwords are not matched!")
                return
            if not self.regexName(unsignedFirstNameEmp, True) or not self.regexName(unsignedLastNameEmp, False):
                self.showMessageBox("Your input name is not incorrectly formatted!")
                return
            if not self.regexAddress(unsignedAddressEmp):
                self.showMessageBox("Your input address is not incorrectly formatted!")
                return
            if not self.regexPassword(unsignedPasswordEmp):
                self.showMessageBox("Your password must be between 8 - 24 in length")
                return
            if not unsignedPasswordEmp == passwordEmp:
                self.showMessageBox("Please turn off Vietnamese Unicode when typing your password!")
                return
            empAge = -(datetime.strptime(birthDayEmp, "%m/%d/%Y").date() - date.today())
            if empAge.days < 18 * 365 + 3:
                print(empAge.days)
                self.showMessageBox("Employee's age must be greater than 18!")
                return

            cursorExc = conn.cursor()
            cursorExc.execute("UPDATE EMPLOYEE SET FISRTNAME = (?), LASTNAME = (?), DATEOFBIRTH = (?)"
                              " ,ADDRESS = (?) WHERE IDEMP = (?) "
                              " UPDATE ACCOUNT SET PASSWORD = (?) WHERE USERNAME = (?)"
                              , (firstNameEmp, lastNameEmp, birthDayEmp, addressEmp
                                 , self.idEmp, passwordEmp, accountNameEmp))
            cursorExc.commit()
            cursorExc.close()
            self.showMessageBox("Update employee information succeeded!")
            self.clickToBackMainEmpWindow()
        except:
            traceback.print_exc()
            self.showMessageBox("Update employee information failed! :((")
            self.clickToBackMainEmpWindow()

    def clickToBackMainEmpWindow(self):
        try:
            self.windowEmployeeMain = QtWidgets.QMainWindow()
            self.ui = employeeMain.Ui_MainWindow()
            self.ui.setupUi(self.windowEmployeeMain, self.idEmp)
            self.windowEmployeeMain.show()
            self.mainWindowCopy.close()
        except:
            traceback.print_exc()

    def showMessageBox(self, message):
        msg = QMessageBox()
        msg.setWindowTitle("Message!")
        msg.setText(message)
        msg.setIcon(QMessageBox.Icon.Information)
        msg.setStandardButtons(QMessageBox.StandardButton.Ok)
        msg.exec()

    def regexName(self, name, isFirstName):
        regexStr = r"[A-Z][a-z]{1,9}" if isFirstName else r"([A-Z][a-z]{1,9}\s){0,5}[A-Z][a-z]{1,9}"
        return re.match(regexStr, name).group() == name if re.match(regexStr, name) is not None else False

    def regexAddress(self, address):
        regexStr = r"[A-Za-z0-9\s\,\.\-\/]{1,150}"
        return re.match(regexStr, address).group() == address \
            if re.match(regexStr, address) is not None else False

    def regexPassword(self, password):
        return re.match(r".{8,24}", password).group() == password \
            if re.match(r".{8,24}", password) is not None else False


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, "7")
    Dialog.show()
    sys.exit(app.exec())
