# Form implementation generated from reading ui file 'dialog_Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import tkinter
import traceback

from PyQt6 import QtCore, QtGui, QtWidgets
import pyodbc
from tkinter import *
from tkinter import messagebox

import admin
import employeeMain
from admin import Ui_MainWindow
import employeeMain


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 10, 391, 20))
        self.label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 71, 16))
        self.label_2.setObjectName("label_2")
        self.inputAccount = QtWidgets.QLineEdit(Dialog)
        self.inputAccount.setGeometry(QtCore.QRect(110, 69, 241, 21))
        self.inputAccount.setObjectName("inputAccount")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 61, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(110, 120, 241, 21))
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.signinBtn = QtWidgets.QPushButton(Dialog)
        self.signinBtn.setGeometry(QtCore.QRect(70, 190, 100, 32))
        self.signinBtn.setObjectName("signinBtn")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(220, 189, 100, 32))
        self.pushButton.setObjectName("pushButton")
        username=self.inputAccount.text()
        password=self.lineEdit.text()
        self.signinBtn.clicked.connect(self.login)
        self.pushButton.clicked.connect(self.exit)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.mainDialogCopy = Dialog
        self.conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                              "Server=localhost;"
                              "Database=HTTM;"
                              "Trusted_connection=yes")

    def login(self):
        try:
            username = self.inputAccount.text()
            password = self.lineEdit.text()
            cursor = self.conn.cursor()
            cursor.execute("SELECT USERNAME, PASSWORD FROM ACCOUNT WHERE USERNAME='"+username+"' AND PASSWORD='"+password+"'")
            user = cursor.fetchone()
            print(user)
            if user is not None:
                master = Tk()
                master.withdraw()
                messagebox.showinfo('Login', 'Yes')
                cursor.execute("SELECT IDROLE, IDEMP FROM ACCOUNT WHERE ACCOUNT.USERNAME = '" + username + "'")
                idUser = cursor.fetchone()
                print(idUser)
                self.openCorrespondingWindow(idUser[1], idUser[0])
                # if idUser[0] == 1:
                #     print()
                #     self.window = QtWidgets.QMainWindow()
                #     self.ui = Ui_MainWindow()
                #     print(type(self.window))
                #     self.ui.setupUi(self.window)
                #     self.window.show()
                #     Dialog.hide()
            else:
                master = Tk()
                master.withdraw()
                messagebox.showinfo('Login', 'Sai tai khoan hoac mat khau. Vui long nhap lai!')

        except:
            traceback.print_exc()
    def exit(self):
        try:
            QtCore.QCoreApplication.instance().quit()
        except:
            traceback.print_exc()
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">ĐĂNG NHẬP</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Tài khoản:"))
        self.label_3.setText(_translate("Dialog", "Mật khẩu:"))
        self.lineEdit.setText(_translate("Dialog", ""))
        self.signinBtn.setText(_translate("Dialog", "Đăng nhập"))
        self.pushButton.setText(_translate("Dialog", "Thoát"))

    def openCorrespondingWindow(self, idEmp, idRole):
        try:
            self.windowEmployeeMain = QtWidgets.QMainWindow()
            if idRole != 1:
                self.ui = employeeMain.Ui_MainWindow()
                self.ui.setupUi(self.windowEmployeeMain, idEmp)
            else:
                self.ui = admin.Ui_MainWindow()
                self.ui.setupUi(self.windowEmployeeMain)
            self.windowEmployeeMain.show()
            self.mainDialogCopy.close()
        except:
            traceback.print_exc()


if __name__ == "__main__":
    sever = 'localhost'
    database = 'HTTM'
    print(pyodbc.drivers())
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
