# Form implementation generated from reading ui file 'dialog_EmployeeCV.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback

import pyodbc
from PyQt6 import QtCore, QtGui, QtWidgets
import dialog_EmployeeInfo


class Ui_Dialog(object):
    def setupUi(self, Dialog, idEmpPara):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 262)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 13, 401, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lblEngLevel = QtWidgets.QLabel(Dialog)
        self.lblEngLevel.setGeometry(QtCore.QRect(145, 60, 111, 16))
        self.lblEngLevel.setObjectName("lblEngLevel")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 151, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lblGroupSkill = QtWidgets.QLabel(Dialog)
        self.lblGroupSkill.setGeometry(QtCore.QRect(170, 92, 51, 16))
        self.lblGroupSkill.setObjectName("lblGroupSkill")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 81, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lblExperience = QtWidgets.QLabel(Dialog)
        self.lblExperience.setGeometry(QtCore.QRect(110, 120, 81, 16))
        self.lblExperience.setObjectName("lblExperience")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lblAcaLvl = QtWidgets.QLabel(Dialog)
        self.lblAcaLvl.setGeometry(QtCore.QRect(130, 150, 58, 16))
        self.lblAcaLvl.setObjectName("lblAcaLvl")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(20, 180, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lblComLvl = QtWidgets.QLabel(Dialog)
        self.lblComLvl.setGeometry(QtCore.QRect(135, 180, 58, 16))
        self.lblComLvl.setObjectName("lblComLvl")
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(310, 210, 61, 31))
        self.btnOk.setObjectName("btnOk")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.dialogCopy = Dialog
        self.idEmp = idEmpPara

        self.loadDataFromDB()
        self.btnOk.clicked.connect(self.clickToBackEmpInfo)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">THÔNG TIN CV</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Trình độ ngoại ngữ:"))
        self.lblEngLevel.setText(_translate("Dialog", ""))
        self.label_4.setText(_translate("Dialog", "Kỹ năng làm việc nhóm:"))
        self.lblGroupSkill.setText(_translate("Dialog", ""))
        self.label_6.setText(_translate("Dialog", "Kinh nghiệm:"))
        self.lblExperience.setText(_translate("Dialog", ""))
        self.label_9.setText(_translate("Dialog", "Trình độ học vấn:"))
        self.lblAcaLvl.setText(_translate("Dialog", ""))
        self.label_11.setText(_translate("Dialog", "Kĩ năng giao tiếp:"))
        self.lblComLvl.setText(_translate("Dialog", ""))
        self.btnOk.setText(_translate("Dialog", "Ok"))

    def loadDataFromDB(self):
        conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                              "Server=localhost;"
                              "Database=HTTM;"
                              "Trusted_connection=yes;"
                              "MARS_Connection=yes")
        cursor = conn.cursor()
        cursor.execute("""SELECT * FROM CV WHERE IDEMP = (?)""", self.idEmp)
        sqlQueryResult = cursor.fetchall()
        for element in sqlQueryResult:
            self.lblEngLevel.setText(element[1])
            self.lblGroupSkill.setText(element[2])
            self.lblExperience.setText(element[3])
            self.lblAcaLvl.setText(element[4])
            self.lblComLvl.setText(element[5])

    def clickToBackEmpInfo(self):
        try:
            self.windowEmployeeInfo = QtWidgets.QDialog()
            self.ui = dialog_EmployeeInfo.Ui_Dialog()
            self.ui.setupUi(self.windowEmployeeInfo, self.idEmp)
            self.windowEmployeeInfo.show()
            self.dialogCopy.close()
        except:
            traceback.print_exc()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, "7")
    Dialog.show()
    sys.exit(app.exec())
