# Form implementation generated from reading ui file 'Employee.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback

import pyodbc
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QDate
import dialog_CreateAccount


class Ui_admin(object):
    def setupUi(self, admin):
        admin.setObjectName("admin")
        admin.resize(1100, 480)
        admin.setIconSize(QtCore.QSize(20, 20))
        admin.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(admin)
        self.centralwidget.setObjectName("centralwidget")
        self.tableNhanVien = QtWidgets.QTableWidget(self.centralwidget)
        self.tableNhanVien.setGeometry(QtCore.QRect(0, 0, 1101, 271))
        self.tableNhanVien.setObjectName("tableNhanVien")
        self.tableNhanVien.setColumnCount(11)
        self.tableNhanVien.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableNhanVien.setHorizontalHeaderItem(10, item)
        self.addBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(780, 280, 100, 32))
        self.addBtn.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addBtn.setFont(font)
        self.addBtn.setObjectName("addBtn")
        self.deleteBtn = QtWidgets.QPushButton(self.centralwidget)
        self.deleteBtn.setGeometry(QtCore.QRect(940, 330, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setObjectName("deleteBtn")
        self.editBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editBtn.setGeometry(QtCore.QRect(940, 280, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editBtn.setFont(font)
        self.editBtn.setObjectName("editBtn")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(980, 410, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(430, 410, 31, 16))
        self.label_10.setObjectName("label_10")
        self.addCVBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addCVBtn.setGeometry(QtCore.QRect(460, 400, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addCVBtn.setFont(font)
        self.addCVBtn.setObjectName("addCVBtn")
        self.editCVBtn = QtWidgets.QPushButton(self.centralwidget)
        self.editCVBtn.setGeometry(QtCore.QRect(540, 400, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editCVBtn.setFont(font)
        self.editCVBtn.setObjectName("editCVBtn")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 280, 391, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.firstnameEmp = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstnameEmp.setFont(font)
        self.firstnameEmp.setText("")
        self.firstnameEmp.setObjectName("firstnameEmp")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.firstnameEmp)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.lastnameEmp = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lastnameEmp.setFont(font)
        self.lastnameEmp.setObjectName("lastnameEmp")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lastnameEmp)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.dobEmp = QtWidgets.QDateEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dobEmp.setFont(font)
        self.dobEmp.setObjectName("dobEmp")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dobEmp)
        self.idEmp = QtWidgets.QLabel(self.formLayoutWidget)
        self.idEmp.setObjectName("idEmp")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.idEmp)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.genderCbb = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.genderCbb.setFont(font)
        self.genderCbb.setObjectName("genderCbb")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.genderCbb)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.addressEmp = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addressEmp.setFont(font)
        self.addressEmp.setObjectName("addressEmp")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.addressEmp)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.ratingEmp = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ratingEmp.setFont(font)
        self.ratingEmp.setObjectName("ratingEmp")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ratingEmp)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(429, 320, 261, 51))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_11)
        self.majorCbb = QtWidgets.QComboBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.majorCbb.setFont(font)
        self.majorCbb.setObjectName("majorCbb")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.majorCbb)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_12)
        self.depCbb = QtWidgets.QComboBox(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.depCbb.setFont(font)
        self.depCbb.setObjectName("depCbb")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.depCbb)
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(780, 330, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resetBtn.setFont(font)
        self.resetBtn.setObjectName("resetBtn")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(430, 290, 60, 21))
        self.label_13.setObjectName("label_13")
        self.viewAccountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.viewAccountBtn.setGeometry(QtCore.QRect(500, 280, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.viewAccountBtn.setFont(font)
        self.viewAccountBtn.setObjectName("viewAccountBtn")
        self.createAccountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.createAccountBtn.setGeometry(QtCore.QRect(580, 280, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.createAccountBtn.setFont(font)
        self.createAccountBtn.setObjectName("createAccountBtn")
        admin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(admin)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        admin.setStatusBar(self.statusbar)
        self.actionTheem = QtGui.QAction(admin)
        self.actionTheem.setObjectName("actionTheem")

        self.loadData()
        self.loadCbbMajor()
        self.loadCbbDepartment()
        self.loadGender()
        self.tableNhanVien.clicked.connect(self.clickToShowData)
        self.resetBtn.clicked.connect(self.clickToReset)
        self.addBtn.clicked.connect(self.clickToAdd)
        self.viewAccountBtn.clicked.connect(self.openAccount)
        self.createAccountBtn.clicked.connect(self.openCreatAccount)
        self.addCVBtn.clicked.connect(self.openCV)
        self.retranslateUi(admin)
        QtCore.QMetaObject.connectSlotsByName(admin)

    def loadData(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            print(pyodbc.drivers())
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            cursor = conn.cursor()
            sql = cursor.execute("SELECT * FROM EMPLOYEE")
            print(sql)
            tableRow = 0
            cursor2 = conn.cursor()
            cursor3 = conn.cursor()
            cursor4 = conn.cursor()
            for rowData in sql:
                rowNumber = self.tableNhanVien.rowCount()
                self.tableNhanVien.insertRow(rowNumber)
                for colName, data in enumerate(rowData):
                    if colName == 8:
                        sqlMajor = cursor2.execute("SELECT MAJOR FROM MAJOR WHERE MAJOR.IDMAJOR = " + str(data))
                        tempMajor = str(sqlMajor.fetchone()[0])
                        self.tableNhanVien.setItem(rowNumber, colName, QtWidgets.QTableWidgetItem(tempMajor))
                    elif colName == 10:
                        sqlDep = cursor3.execute("SELECT DEPNAME FROM DEPARTMENT WHERE DEPARTMENT.IDDEP = " +str(data))
                        tempDep = str(sqlDep.fetchone()[0])
                        self.tableNhanVien.setItem(rowNumber, colName, QtWidgets.QTableWidgetItem(tempDep))
                    else:
                        self.tableNhanVien.setItem(rowNumber, colName, QtWidgets.QTableWidgetItem(str(data)))
                    tableRow += 1
        except:
            traceback.print_exc()

    def reloadData(self):
        self.tableNhanVien.set
    def loadCbbMajor(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            print(pyodbc.drivers())
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            cursor = conn.cursor()
            sql = cursor.execute("SELECT * FROM MAJOR")
            for row in sql:
                #print(row[1])
                self.majorCbb.addItem(str(row[1]))
        except:
            traceback.print_exc()
    def loadCbbDepartment(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            print(pyodbc.drivers())
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            cursor = conn.cursor()
            sql = cursor.execute("SELECT * FROM DEPARTMENT")
            for row in sql:
                self.depCbb.addItem(str(row[1]))
        except:
            traceback.print_exc()

    def loadGender(self):
        try:
            gender = ["Nam", "Nữ"]
            for i in gender:
                self.genderCbb.addItem(i)
        except:
            traceback.print_exc()

    def clickToShowData(self):
        try:
            selectedRow = self.tableNhanVien.currentRow()
            self.idEmp.setText(str(self.tableNhanVien.item(selectedRow, 0).text()))
            self.firstnameEmp.setText(str(self.tableNhanVien.item(selectedRow, 1).text()))
            self.lastnameEmp.setText(str(self.tableNhanVien.item(selectedRow, 2).text()))
            temp = QDate.fromString(self.tableNhanVien.item(selectedRow, 3).text(), "yyyy-MM-dd")
            self.dobEmp.setDate(temp)
            self.genderCbb.setItemText(0, self.tableNhanVien.item(selectedRow, 4).text())
            if self.tableNhanVien.item(selectedRow, 4).text() == "Nữ":
                self.genderCbb.setItemText(1, "Nam")
            else:
                self.genderCbb.setItemText(1, "Nữ")
            self.addressEmp.setText(str(self.tableNhanVien.item(selectedRow, 5).text()))
            self.ratingEmp.setText(str(self.tableNhanVien.item(selectedRow, 6).text()))
            self.majorCbb.setCurrentText(str(self.tableNhanVien.item(selectedRow, 8).text()))
            self.depCbb.setCurrentText(str(self.tableNhanVien.item(selectedRow, 10).text()))
        except:
            traceback.print_exc()

    def clickToReset(self):
        try:
            self.idEmp.setText("")
            self.firstnameEmp.setText("")
            self.lastnameEmp.setText("")
            self.genderCbb.setCurrentText("")
            self.addressEmp.setText("")
            self.ratingEmp.setText("")
            self.majorCbb.setCurrentText("")
            self.depCbb.setCurrentText("")
        except:
            traceback.print_exc()

    def clickToAdd(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            firstnameEmp = self.firstnameEmp.text()
            print(firstnameEmp)
            lastnameEmp = self.lastnameEmp.text()
            print(lastnameEmp)
            temp = self.dobEmp.date()
            dobEmp = temp.toString("yyyy-MM-dd")
            print(dobEmp)
            genderEmp = self.genderCbb.currentText()
            print(genderEmp)
            addressEmp = self.addressEmp.text()
            print(addressEmp)
            majorEmp = self.majorCbb.currentText()
            cursor = conn.cursor()
            sqlMajor = cursor.execute("SELECT IDMAJOR FROM MAJOR WHERE MAJOR.MAJOR = '" + str(majorEmp) + "'")
            majorEmpSql = sqlMajor.fetchone()
            print(majorEmpSql[0])
            depEmp = self.depCbb.currentText()
            cursor2 = conn.cursor()
            sqlDep = cursor2.execute("SELECT IDDEP FROM DEPARTMENT WHERE DEPARTMENT.DEPNAME = '" + str(depEmp) + "'")
            depEmpSql = sqlDep.fetchone()
            print(depEmpSql[0])
            cursor = conn.cursor()
            cursor.execute("INSERT INTO EMPLOYEE(FISRTNAME, LASTNAME, DATEOFBIRTH, GENDER, ADDRESS, AVGRATING, IDVC, IDMAJOR, USERNAME, IDDEP) VALUES(?,?,?,?,?,?,?,?,?,?)", (firstnameEmp, lastnameEmp, dobEmp, genderEmp, addressEmp, None, None, majorEmpSql[0], None, depEmpSql[0]))
            cursor.commit()
            self.loadData()
        except:
            traceback.print_exc()

    def openAccount(self):
        try:
            self.windowProject = QtWidgets.QDialog()
            self.ui = dialog_CreateAccount.Ui_Dialog()
            row = self.tableNhanVien.currentRow()
            self.ui.set_id(self.tableNhanVien.item(row, 0).text())
            self.ui.setupUi(self.windowProject)
            self.windowProject.show()
        except:
            traceback.print_exc()

    def openCreatAccount(self):
        try:
            import dialog_CreateAccount1
            self.windowProject = QtWidgets.QMainWindow()
            self.ui = dialog_CreateAccount1.Ui_MainWindow()
            row = self.tableNhanVien.currentRow()
            self.ui.set_id(self.tableNhanVien.item(row, 0).text())
            self.ui.setupUi(self.windowProject)
            self.windowProject.show()
        except:
            traceback.print_exc()

    def openCV(self):
        try:
            import dialog_CV
            self.windowProject=QtWidgets.QMainWindow()
            self.ui=dialog_CV.Ui_Dialog()
            self.ui.setupUi(self.windowProject)
            self.windowProject.show()
        except:
            traceback.print_exc()
    def retranslateUi(self, admin):
        _translate = QtCore.QCoreApplication.translate
        admin.setWindowTitle(_translate("admin", "MainWindow"))
        item = self.tableNhanVien.horizontalHeaderItem(0)
        item.setText(_translate("admin", "ID Nhân viên"))
        item = self.tableNhanVien.horizontalHeaderItem(1)
        item.setText(_translate("admin", "Họ"))
        item = self.tableNhanVien.horizontalHeaderItem(2)
        item.setText(_translate("admin", "Tên"))
        item = self.tableNhanVien.horizontalHeaderItem(3)
        item.setText(_translate("admin", "Ngày sinh"))
        item = self.tableNhanVien.horizontalHeaderItem(4)
        item.setText(_translate("admin", "Giới tính"))
        item = self.tableNhanVien.horizontalHeaderItem(5)
        item.setText(_translate("admin", "Địa chỉ"))
        item = self.tableNhanVien.horizontalHeaderItem(6)
        item.setText(_translate("admin", "Đánh giá"))
        item = self.tableNhanVien.horizontalHeaderItem(7)
        item.setText(_translate("admin", "CV"))
        item = self.tableNhanVien.horizontalHeaderItem(8)
        item.setText(_translate("admin", "Chuyên ngành"))
        item = self.tableNhanVien.horizontalHeaderItem(9)
        item.setText(_translate("admin", "Tài khoản"))
        item = self.tableNhanVien.horizontalHeaderItem(10)
        item.setText(_translate("admin", "Phòng ban"))
        self.addBtn.setText(_translate("admin", "Thêm"))
        self.deleteBtn.setText(_translate("admin", "Xoá"))
        self.editBtn.setText(_translate("admin", "Sửa"))
        self.exitBtn.setText(_translate("admin", "Thoát"))
        self.label_10.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">CV:</span></p></body></html>"))
        self.addCVBtn.setText(_translate("admin", "Thêm"))
        self.editCVBtn.setText(_translate("admin", "Sửa"))
        self.label_3.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">Họ:</span></p></body></html>"))
        self.label_4.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">Tên:</span></p></body></html>"))
        self.label_5.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">Ngày sinh:</span></p></body></html>"))
        self.idEmp.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\"></span></p></body></html>"))
        self.label.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">ID Nhân viên:</span></p></body></html>"))
        self.label_6.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">Giới tính:</span></p></body></html>"))
        self.label_7.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">Địa chỉ:</span></p></body></html>"))
        self.label_8.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">Đánh giá:</span></p></body></html>"))
        self.label_11.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">Chuyên ngành:</span></p></body></html>"))
        self.label_12.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">Phòng ban:</span></p></body></html>"))
        self.resetBtn.setText(_translate("admin", "Reset"))
        self.label_13.setText(_translate("admin", "<html><head/><body><p><span style=\" font-size:12pt;\">Tài khoản: </span></p></body></html>"))
        self.viewAccountBtn.setText(_translate("admin", "Xem"))
        self.createAccountBtn.setText(_translate("admin", "Tạo"))
        self.actionTheem.setText(_translate("admin", "Theem"))


if __name__ == "__main__":
    sever = 'localhost'
    database = 'HTTM'
    conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                          "Server=localhost;"
                          "Database=HTTM;"
                          "Trusted_connection=yes;"
                          "MARS_Connection=yes")
    import sys
    app = QtWidgets.QApplication(sys.argv)
    admin = QtWidgets.QMainWindow()
    ui = Ui_admin()
    ui.setupUi(admin)
    admin.show()
    sys.exit(app.exec())
