# Form implementation generated from reading ui file 'employeeMain.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback

from PyQt6 import QtCore, QtGui, QtWidgets

import employeeProduct
import dialog_EmployeeInfo
import dialog_Login

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, idEmpPara):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(312, 223)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 311, 30))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 60, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 180, 100, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.mainWindowCopy = MainWindow
        self.idEmp = idEmpPara

        self.pushButton.clicked.connect(self.clickToOpenProject)
        self.pushButton_2.clicked.connect(self.clickToOpenEmpInfo)
        self.pushButton_3.clicked.connect(self.clickToReturnLoginWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">NHÂN VIÊN</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Đồ án"))
        self.pushButton_2.setText(_translate("MainWindow", "Thông tin cá nhân"))
        self.pushButton_3.setText(_translate("MainWindow", "Thoát"))

    def clickToOpenProject(self):
        try:
            self.windowEmployeeProject = QtWidgets.QMainWindow()
            self.ui = employeeProduct.Ui_MainWindow()
            self.ui.setupUi(self.windowEmployeeProject, self.idEmp)
            self.windowEmployeeProject.show()
            self.mainWindowCopy.close()
        except:
            traceback.print_exc()

    def clickToOpenEmpInfo(self):
        try:
            self.windowEmployeeInfo = QtWidgets.QDialog()
            self.ui = dialog_EmployeeInfo.Ui_Dialog()
            self.ui.setupUi(self.windowEmployeeInfo, self.idEmp)
            self.windowEmployeeInfo.show()
            self.mainWindowCopy.close()
        except:
            traceback.print_exc()

    def clickToReturnLoginWindow(self):
        try:
            self.windowDiaLogin = QtWidgets.QDialog()
            self.ui = dialog_Login.Ui_Dialog()
            self.ui.setupUi(self.windowDiaLogin)
            self.windowDiaLogin.show()
            self.mainWindowCopy.close()
        except:
            traceback.print_exc()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow, "8")
    MainWindow.show()
    sys.exit(app.exec())
