# Form implementation generated from reading ui file 'Major.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback

import pyodbc
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 12, 711, 31))
        self.label.setObjectName("label")
        self.tableMajor = QtWidgets.QTableWidget(self.centralwidget)
        self.tableMajor.setGeometry(QtCore.QRect(20, 60, 401, 231))
        self.tableMajor.setMinimumSize(QtCore.QSize(0, 0))
        self.tableMajor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableMajor.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableMajor.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableMajor.setFont(font)
        self.tableMajor.setMidLineWidth(0)
        self.tableMajor.setObjectName("tableMajor")
        self.tableMajor.setColumnCount(2)
        self.tableMajor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMajor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableMajor.setHorizontalHeaderItem(1, item)
        self.tableMajor.horizontalHeader().setDefaultSectionSize(200)
        self.btnAddMajor = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddMajor.setGeometry(QtCore.QRect(440, 141, 111, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAddMajor.setFont(font)
        self.btnAddMajor.setObjectName("btnAddMajor")
        self.btnExitMajor = QtWidgets.QPushButton(self.centralwidget)
        self.btnExitMajor.setGeometry(QtCore.QRect(599, 260, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnExitMajor.setFont(font)
        self.btnExitMajor.setObjectName("btnExitMajor")
        self.btnDelMajor = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelMajor.setGeometry(QtCore.QRect(588, 140, 111, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDelMajor.setFont(font)
        self.btnDelMajor.setObjectName("btnDelMajor")
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setGeometry(QtCore.QRect(440, 190, 111, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEdit.setFont(font)
        self.btnEdit.setObjectName("btnEdit")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(439, 60, 261, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.idMajor = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idMajor.setFont(font)
        self.idMajor.setObjectName("idMajor")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.idMajor)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.inputMajor = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputMajor.setFont(font)
        self.inputMajor.setObjectName("inputMajor")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputMajor)
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(590, 190, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnReset.setFont(font)
        self.btnReset.setObjectName("btnReset")
        MainWindow.setCentralWidget(self.centralwidget)

        self.loadData()
        self.tableMajor.clicked.connect(self.clickToShowData)
        self.btnEdit.clicked.connect(self.clickToEdit)
        self.btnAddMajor.clicked.connect(self.clickToAdd)
        self.btnDelMajor.clicked.connect(self.clickToDel)
        self.btnReset.clicked.connect(self.clickToReset)
        try:
            self.btnExitMajor.clicked.connect(MainWindow.close)
            self.btnExitMajor.clicked.connect(self.openAdmin)
        except:
            traceback.print_exc()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def loadData(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            cursor = conn.cursor()
            sql = cursor.execute("SELECT * FROM MAJOR")
            for rowData in sql:
                rowNumber = self.tableMajor.rowCount()
                self.tableMajor.insertRow(rowNumber)
                for colName, data in enumerate(rowData):
                    self.tableMajor.setItem(rowNumber, colName, QtWidgets.QTableWidgetItem(str(data)))
        except:
            traceback.print_exc()

    def setTableRow(self):
        while self.tableMajor.rowCount() > 0:
            self.tableMajor.removeRow(0)

    def clickToShowData(self):
        try:
            selectedRow = self.tableMajor.currentRow()
            self.idMajor.setText(self.tableMajor.item(selectedRow, 0).text())
            self.inputMajor.setText(self.tableMajor.item(selectedRow, 1).text())
        except:
            traceback.print_exc()

    def clickToEdit(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            idMajor = self.idMajor.text()
            inputNew = self.inputMajor.text()
            cursor = conn.cursor()
            cursor.execute("UPDATE MAJOR SET MAJOR = '" + inputNew + "' WHERE MAJOR.IDMAJOR = '" + str(idMajor) + "'")
            cursor.commit()
            self.setTableRow()
            self.loadData()
        except:
            traceback.print_exc()

    def clickToAdd(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            inputMajor = self.inputMajor.text()
            cursor = conn.cursor()
            cursor.execute("INSERT INTO MAJOR(MAJOR) VALUES(?)", (inputMajor))
            cursor.commit()
            self.setTableRow()
            self.loadData()
        except:
            traceback.print_exc()

    def clickToDel(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            idMajor = self.idMajor.text()
            print(idMajor)
            cursor = conn.cursor()
            cursor.execute("DELETE FROM MAJOR WHERE MAJOR.IDMAJOR = '" + idMajor + "'")
            cursor.commit()
            self.setTableRow()
            self.loadData()
        except:
            traceback.print_exc()

    def clickToReset(self):
        try:
            self.inputMajor.setText("")
            self.idMajor.setText("")
        except:
            traceback.print_exc()

    def openAdmin(self):
        try:
            import admin
            self.windowProject = QtWidgets.QMainWindow()
            self.ui = admin.Ui_MainWindow()
            self.ui.setupUi(self.windowProject)
            self.windowProject.show()
        except:
            traceback.print_exc()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">THÔNG TIN CHUYÊN NGÀNH</span></p></body></html>"))
        item = self.tableMajor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Chuyên ngành"))
        item = self.tableMajor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên"))
        self.btnAddMajor.setText(_translate("MainWindow", "Thêm"))
        self.btnExitMajor.setText(_translate("MainWindow", "Thoát"))
        self.btnDelMajor.setText(_translate("MainWindow", "Xoá"))
        self.btnEdit.setText(_translate("MainWindow", "Sửa"))
        self.label_4.setText(_translate("MainWindow", "ID:"))
        self.label_3.setText(_translate("MainWindow", "Tên:"))
        self.btnReset.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
