# Form implementation generated from reading ui file 'Role.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback

import pyodbc
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tableRole(object):
    def setupUi(self, tableRole):
        tableRole.setObjectName("tableRole")
        tableRole.resize(654, 292)
        self.centralwidget = QtWidgets.QWidget(tableRole)
        self.centralwidget.setObjectName("centralwidget")
        self.btnEditRole = QtWidgets.QPushButton(self.centralwidget)
        self.btnEditRole.setGeometry(QtCore.QRect(420, 190, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnEditRole.setFont(font)
        self.btnEditRole.setObjectName("btnEditRole")
        self.btnAddRole = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddRole.setGeometry(QtCore.QRect(420, 140, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAddRole.setFont(font)
        self.btnAddRole.setObjectName("btnAddRole")
        self.btnDelRole = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelRole.setGeometry(QtCore.QRect(540, 140, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDelRole.setFont(font)
        self.btnDelRole.setObjectName("btnDelRole")
        self.btnExitRole = QtWidgets.QPushButton(self.centralwidget)
        self.btnExitRole.setGeometry(QtCore.QRect(540, 250, 100, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnExitRole.setFont(font)
        self.btnExitRole.setObjectName("btnExitRole")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 651, 31))
        self.label.setObjectName("label")
        self.tableRole_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableRole_2.setGeometry(QtCore.QRect(10, 50, 401, 231))
        self.tableRole_2.setObjectName("tableRole_2")
        self.tableRole_2.setColumnCount(2)
        self.tableRole_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableRole_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableRole_2.setHorizontalHeaderItem(1, item)
        self.tableRole_2.horizontalHeader().setDefaultSectionSize(200)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(420, 50, 221, 80))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.inputRole = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputRole.setFont(font)
        self.inputRole.setObjectName("inputRole")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputRole)
        self.idRole = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idRole.setFont(font)
        self.idRole.setObjectName("idRole")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.idRole)
        self.btnResetRole = QtWidgets.QPushButton(self.centralwidget)
        self.btnResetRole.setGeometry(QtCore.QRect(540, 190, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnResetRole.setFont(font)
        self.btnResetRole.setObjectName("btnResetRole")
        tableRole.setCentralWidget(self.centralwidget)

        self.loadData()
        self.tableRole_2.clicked.connect(self.clickToShowData)
        self.btnEditRole.clicked.connect(self.clickToEdit)
        self.btnAddRole.clicked.connect(self.clickToAdd)
        self.btnDelRole.clicked.connect(self.clickToDel)
        self.btnResetRole.clicked.connect(self.clickToReset)
        try:
            self.btnExitRole.clicked.connect(tableRole.close)
            self.btnExitRole.clicked.connect(self.openAdmin)
        except:
            traceback.print_exc()

        self.retranslateUi(tableRole)
        QtCore.QMetaObject.connectSlotsByName(tableRole)

    def loadData(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            cursor = conn.cursor()
            sql = cursor.execute("SELECT * FROM ROLE")
            for rowData in sql:
                rowNumber = self.tableRole_2.rowCount()
                self.tableRole_2.insertRow(rowNumber)
                for colName, data in enumerate(rowData):
                    self.tableRole_2.setItem(rowNumber, colName, QtWidgets.QTableWidgetItem(str(data)))
        except:
            traceback.print_exc()

    def setTableRow(self):
        while self.tableRole_2.rowCount() > 0:
            self.tableRole_2.removeRow(0)

    def clickToShowData(self):
        try:
            selectedRow = self.tableRole_2.currentRow()
            self.idRole.setText(self.tableRole_2.item(selectedRow, 0).text())
            self.inputRole.setText(self.tableRole_2.item(selectedRow, 1).text())
        except:
            traceback.print_exc()

    def clickToEdit(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            idRole = self.idRole.text()
            inputRole = self.inputRole.text()
            cursor = conn.cursor()
            cursor.execute("UPDATE ROLE SET ROLENAME = '" + inputRole + "' WHERE ROLE.IDROLE = '" + str(idRole) + "'")
            cursor.commit()
            self.setTableRow()
            self.loadData()
        except:
            traceback.print_exc()

    def clickToAdd(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            inputRole = self.inputRole.text()
            cursor = conn.cursor()
            cursor.execute("INSERT INTO ROLE(ROLENAME) VALUES(?)", (inputRole))
            cursor.commit()
            self.setTableRow()
            self.loadData()
        except:
            traceback.print_exc()

    def clickToDel(self):
        try:
            sever = 'localhost'
            database = 'HTTM'
            conn = pyodbc.connect("DRIVER={SQL Server Native Client 11.0};"
                                  "Server=localhost;"
                                  "Database=HTTM;"
                                  "Trusted_connection=yes;"
                                  "MARS_Connection=yes")
            idRole = self.idRole.text()
            cursor = conn.cursor()
            cursor.execute("DELETE FROM ROLE WHERE ROLE.IDROLE = '" + idRole + "'")
            cursor.commit()
            self.setTableRow()
            self.loadData()
        except:
            traceback.print_exc()

    def clickToReset(self):
        try:
            self.inputRole.setText("")
            self.idRole.setText("")
        except:
            traceback.print_exc()

    def openAdmin(self):
        try:
            import admin
            self.windowProject = QtWidgets.QMainWindow()
            self.ui = admin.Ui_MainWindow()
            self.ui.setupUi(self.windowProject)
            self.windowProject.show()
        except:
            traceback.print_exc()

    def retranslateUi(self, tableRole):
        _translate = QtCore.QCoreApplication.translate
        tableRole.setWindowTitle(_translate("tableRole", "MainWindow"))
        self.btnEditRole.setText(_translate("tableRole", "Sửa"))
        self.btnAddRole.setText(_translate("tableRole", "Thêm"))
        self.btnDelRole.setText(_translate("tableRole", "Xoá"))
        self.btnExitRole.setText(_translate("tableRole", "Thoát"))
        self.label.setText(_translate("tableRole", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700;\">THÔNG TIN QUYỀN</span></p><p align=\"center\"><br/></p></body></html>"))
        item = self.tableRole_2.horizontalHeaderItem(0)
        item.setText(_translate("tableRole", "ID Quyền"))
        item = self.tableRole_2.horizontalHeaderItem(1)
        item.setText(_translate("tableRole", "Tên"))
        self.label_4.setText(_translate("tableRole", "ID:"))
        self.label_3.setText(_translate("tableRole", "Tên:"))
        self.btnResetRole.setText(_translate("tableRole", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tableRole = QtWidgets.QMainWindow()
    ui = Ui_tableRole()
    ui.setupUi(tableRole)
    tableRole.show()
    sys.exit(app.exec())
